"""Proof artifact generation and verification via Z3 + SMT-LIB.

Two paths:
  - generate: claim + function body → SMT-LIB problem statement (.smt2)
  - check:    .smt2 → invoke Z3 → confirm `unsat` (= claim holds)

The encoding lives entirely in this module — `model` knows nothing about SMT.

Today's coverage (matches the body lowering surface):
  expressions: IntLit, ParamRef, BinOp(add, slt)
  statements:  ReturnInt, ReturnExpr, If (both branches return), CallPuts (skipped)
  claims:      NonNegativeClaim, IntRangeClaim (as hypotheses on params),
               ReturnInRangeClaim (as goals on the return value)

Bodies that contain user-function Calls or fall-through-without-return raise
NotImplementedError. The smt-lowering is intentionally narrow: extending it is
the next move for richer demos.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass

from cpg.model import (
    BinOp,
    Call,
    CallPuts,
    Claim,
    Function,
    If,
    IntLit,
    IntRangeClaim,
    NonNegativeClaim,
    ParamRef,
    ReturnExpr,
    ReturnInRangeClaim,
    ReturnInt,
    claim_param,
)


# i32 bounds — used as the universe for parameters when no claim narrows them.
I32_MIN = -2**31
I32_MAX = 2**31 - 1


# ---------- Body → SMT ----------

def _expr_to_smt(expr) -> str:
    match expr:
        case IntLit(value=v):
            return str(v)
        case ParamRef(name=n):
            return n
        case BinOp(op="add", lhs=l, rhs=r):
            return f"(+ {_expr_to_smt(l)} {_expr_to_smt(r)})"
        case BinOp(op="slt", lhs=l, rhs=r):
            return f"(< {_expr_to_smt(l)} {_expr_to_smt(r)})"
        case Call(function=fname):
            raise NotImplementedError(
                f"can't lower Call to {fname!r} for SMT (no Call modelling yet)"
            )
    raise NotImplementedError(f"can't lower expr {expr!r} for SMT")


def _stmts_to_return_smt(stmts) -> str:
    """Translate a sequence of statements into the SMT term for the eventual
    return value. Side-effect-only statements (CallPuts) are skipped."""
    for stmt in stmts:
        match stmt:
            case ReturnInt(value=v):
                return str(v)
            case ReturnExpr(value=expr):
                return _expr_to_smt(expr)
            case If(cond=cond, then_body=t, else_body=e):
                return (
                    f"(ite {_expr_to_smt(cond)} "
                    f"{_stmts_to_return_smt(list(t))} "
                    f"{_stmts_to_return_smt(list(e))})"
                )
            case CallPuts():
                continue  # side effect only; doesn't influence return value
            case _:
                raise NotImplementedError(f"can't lower stmt {stmt!r} for SMT")
    raise NotImplementedError("function body has no terminating return")


def function_return_term(fn: Function) -> str:
    """SMT-LIB Int-valued term representing fn's return value as a function of
    its parameters."""
    return _stmts_to_return_smt(list(fn.body))


# ---------- Claim → SMT predicate ----------

def claim_smt_predicate(c: Claim, return_term: str) -> str:
    """SMT-LIB Bool-valued predicate the claim *asserts*.

    Param-scoped claims read the param by name. Return-scoped claims read
    the supplied return-value term.
    """
    match c:
        case NonNegativeClaim(param=p):
            return f"(>= {p} 0)"
        case IntRangeClaim(param=p, min=lo, max=hi):
            return _range_pred(p, lo, hi)
        case ReturnInRangeClaim(min=lo, max=hi):
            return _range_pred(return_term, lo, hi)
    raise NotImplementedError(f"can't lower claim {c!r} for SMT")


def _range_pred(term: str, lo: int | None, hi: int | None) -> str:
    parts: list[str] = []
    if lo is not None:
        parts.append(f"(>= {term} {lo})")
    if hi is not None:
        parts.append(f"(<= {term} {hi})")
    if not parts:
        return "true"
    if len(parts) == 1:
        return parts[0]
    return f"(and {' '.join(parts)})"


# ---------- Full SMT-LIB problem ----------

def goal_smt_lib(fn: Function, goal: Claim, *, hypotheses: tuple[Claim, ...] = ()) -> str:
    """Build a full SMT-LIB problem that's `unsat` iff `goal` holds for `fn`.

    Strategy: assert hypotheses as facts; assert NEGATION of goal; ask Z3 to
    find a model. unsat = no counterexample = goal holds.
    """
    return_term = function_return_term(fn)

    lines: list[str] = []
    lines.append(f"; auto-generated by cpg.proof for function {fn.name}")
    lines.append(f"; goal: {goal!r}")
    lines.append("(set-logic QF_LIA)")
    lines.append("")

    for p in fn.params:
        lines.append(f"(declare-const {p} Int)")
        # Bound params to the i32 universe; otherwise Z3 finds counterexamples
        # in the unbounded integers that don't apply to our actual codegen.
        lines.append(f"(assert (>= {p} {I32_MIN}))")
        lines.append(f"(assert (<= {p} {I32_MAX}))")

    if hypotheses:
        lines.append("")
        lines.append("; hypotheses (existing claims as premises)")
        for h in hypotheses:
            lines.append(f";   {h.kind}({claim_param(h) or 'return'})")
            lines.append(f"(assert {claim_smt_predicate(h, return_term)})")

    lines.append("")
    lines.append("; goal (negated; we ask Z3 to find a counterexample)")
    lines.append(f"(assert (not {claim_smt_predicate(goal, return_term)}))")
    lines.append("")
    lines.append("(check-sat)")
    lines.append("(exit)")
    return "\n".join(lines) + "\n"


# ---------- Z3 invocation ----------

@dataclass(frozen=True)
class Z3Result:
    status: str   # "unsat" | "sat" | "unknown"
    raw: str      # full stdout for debugging


class Z3NotInstalled(RuntimeError):
    pass


def run_z3_on_smt(smt: str, *, timeout_s: float = 10.0) -> Z3Result:
    """Pipe SMT-LIB content to z3 via stdin and parse its first-line answer."""
    if shutil.which("z3") is None:
        raise Z3NotInstalled("z3 binary not found in PATH (install with `pacman -S z3`)")
    proc = subprocess.run(
        ["z3", "-in"],
        input=smt,
        capture_output=True, text=True, timeout=timeout_s, check=False,
    )
    out = (proc.stdout or "").strip()
    first = out.splitlines()[0].strip() if out else ""
    if first not in ("sat", "unsat", "unknown"):
        raise RuntimeError(
            f"z3 returned unexpected output:\nstdout: {proc.stdout!r}\n"
            f"stderr: {proc.stderr!r}\nrc: {proc.returncode}"
        )
    return Z3Result(status=first, raw=proc.stdout)


def run_z3_on_file(path) -> Z3Result:
    """Run z3 on an .smt2 file directly. Used by verify-claims."""
    if shutil.which("z3") is None:
        raise Z3NotInstalled("z3 binary not found in PATH (install with `pacman -S z3`)")
    proc = subprocess.run(
        ["z3", str(path)],
        capture_output=True, text=True, timeout=10.0, check=False,
    )
    out = (proc.stdout or "").strip()
    first = out.splitlines()[0].strip() if out else ""
    if first not in ("sat", "unsat", "unknown"):
        raise RuntimeError(
            f"z3 returned unexpected output:\nstdout: {proc.stdout!r}\n"
            f"stderr: {proc.stderr!r}\nrc: {proc.returncode}"
        )
    return Z3Result(status=first, raw=proc.stdout)
